image: golang:1.16-alpine

stages:
  - build
  - publish
  - deploy
  - e2e
  - post-deploy
  - close

build:
  stage: build
  script:
    - echo "Build"
  only:
    - master
    - /^(release|hotfix|feature)\/.+$/

unit:
  stage: build
  script:
    - echo "Unit testing"
  only:
    - /^(release|test)\/.+$/

linter:
  stage: build
  script:
    - echo "Linter"
  only:
    - /^(release|test)\/.+$/

create image:
  stage: publish
  script:
    - echo "Create image for dev/stg"
  only:
    - master
    - /^(release|hotfix|feature)\/.+$/

release image:
  stage: publish
  script:
    - echo "Create image for prod"
  only:
    refs:
      - tags
  except:
    - /^(release|hotfix|feature|test)\/.+$/

development:
  stage: deploy
  script:
    - echo "Deploy to dev environment"
  when: manual
  only:
    - master
    - /^(feature)\/.+$/

staging:
  stage: deploy
  script:
    - echo "Deploy to stg environment"
  only:
    - /^(release|hotfix)\/.+$/

staging latest:
  stage: deploy
  script:
    - echo "Update stg with last version"
  only:
    - master
  except:
    - /^(release|hotfix|feature|test)\/.+$/

production:
  stage: deploy
  script:
    - echo "Deploy to prod environment"
  when: manual
  only:
    refs:
      - tags
  except:
    - /^(release|hotfix|feature|test)\/.+$/

test:
  stage: e2e
  script:
    - echo "API testing on stg"
  allow_failure: true
  only:
    - /^(release|test)\/.+$/

ready to prod:
  stage: close
  script:
    - echo "Ready to prod"
  when: manual
  only:
    - /^(release|hotfix)\/.+$/

close release:
  stage: close
  script:
    - echo "Ready to prod"
  when: manual
  only:
    refs:
      - tags
  except:
    - /^(release|hotfix|feature|test)\/.+$/