image: golang:1.16-alpine

stages:
  - test

test:
  image: pricec/gotestsum:latest
  stage: test
  before_script:
    - go get gotest.tools/gotestsum
  script:
    - gotestsum --jsonfile json-report.txt --format testname  -- -coverprofile=cover.out ./homeworks/homework9/greeter/
  artifacts:
    when: always
    expire_in: 1 days
    paths:
      - json-report.txt
