image: golang:1.16-alpine

stages:
  - lint
  - test

lint:
  image: golangci/golangci-lint:v1.43
  stage: lint
  script:
    - golangci-lint run -v ./...
  allow_failure: true

test:
  image: pricec/gotestsum:latest
  stage: test
  before_script:
    - go get gotest.tools/gotestsum
  script:
    - gotestsum --jsonfile json-report.txt --format testname  -- -coverprofile=cover.out ./homeworks/homework9/greeter/
  artifacts:
    when: always
    expire_in: 1 days
    paths:
      - json-report.txt
  allow_failure: true
